import Navbar from './components/Navbar';

const Layout = ({ children }) => {
  return (
      <html lang="en">
          <head>
              <title>My Next.js App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </head>
          <body>
              <Navbar />
              <main>{children}</main>
          </body>
      </html>
  );
};

export default Layout;